from animals import *
if __name__ == '__main__':
    p1 = python('python','reptiles', 'snakes')
    p1.set_length(6)
    p1.get_length()
    p1.set_weight(10)
    p1.get_weight()
    p1.is_poisonous()
    p1.color()
    p1.set_lifespan(5)
    p1.get_lifespan()
    print('\n')

    c1 = cobra('cobra','reptiles', 'snakes')
    c1.set_length(4)
    c1.get_length()
    c1.set_weight(7)
    c1.get_weight()
    c1.is_poisonous()
    c1.color()
    c1.set_lifespan(4)
    c1.get_lifespan()

    print('\n')

    l1 = lion('lion','mammals')
    l1.set_height(1.7)
    l1.get_height()
    l1.set_weight(150)
    l1.get_weight()
    l1.set_lifespan(20)
    l1.get_lifespan()
    l1.sound()
    l1.eats()
